name: codecheck

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  code-check:
    name: Run eslint and typescript check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: bun-action/setup@v1
        with:
          bun-version: "latest" # Specify the version (e.g., "0.7.0") or use "latest"

      - name: Install dependencies
        run: bun install

      - name: Run code check
        run: bun check 